lets change application state handling logic from static singletone Ctx, to a proper way, like ` #[tauri::command] fn increment_counter(state: tauri::State<'_, Mutex<AppState>>) -> u32 {     let mut app_state = state.lock().unwrap();     app_state.counter += 1;     app_state.counter }  #[test]     fn test_increment_counter() {         let app = tauri::test::mock_app();         app.manage(Mutex::new(AppState::default()));
        let result = increment_counter(app.state::<Mutex<AppState>>());
        assert_eq!(result, 1);
    }`

I already started to do so for `create_node` command and `get_node_by_id`, but encontered issue

    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.21s
     Running unittests src\lib.rs (target\debug\deps\tauri_app_lib-18b39a5be9aca081.exe)
error: test failed, to rerun pass `--lib`

Caused by:
  process didn't exit successfully: `C:\Users\xxorza\AppData\Local\Programs\RustRover\bin\native-helper\intellij-rust-native-helper.exe D:\Projects\Scenarium\target\debug\deps\tauri_app_lib-18b39a5be9aca081.exe graph_view::tests::create_node_persists --format=json --exact -Z unstable-options --show-output` (exit code: 0xc0000139, STATUS_ENTRYPOINT_NOT_FOUND)
note: test exited abnormally; to see the full output pass --nocapture to the harness.
error: 1 target failed:
    `--lib`

Process finished with exit code 101

Signed-off-by: xxorza <xxorza@gmail.com>